#!/usr/bin/env bash
# This script displays listening ports and their associated PID/Program name.

# Use netstat to get the active Internet connections. 
# -l option to display listening sockets and 
# --program to show the associated program name and PID.
netstat -l --program
