#!/usr/bin/env bash
# Script to display a list of currently running processes

# Display the header
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Use ps command to display processes with hierarchy
ps aux --forest | head -50 | awk '{printf "%-10s %-4s %-4s %-6s %-6s %-4s %-6s %-5s %-5s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10}'
