#!/usr/bin/env bash
# This script displays messages based on loop iteration

counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "Bad Luck"
    elif [ $counter -eq 8 ]; then
        echo "Good Luck"
    else
        echo "Best School"
    fi

    ((counter++))
done